# Configuration for the Read The Docs (RTD) builds of the documentation.
# Ref: https://docs.readthedocs.io/en/stable/config-file/v2.html
# Note python.install.requirements is not currently required, as Sphinx is
# preinstalled and spelling checks not performed by RTD.
version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"

sphinx:
  configuration: docs/conf.py

formats:
  - epub
  - pdf
  - htmlzip
